### PR TITLE
Env file support

### PR DESCRIPTION
**Pull request by bound2**
Created an abstraction layer in config to support config.ts or config from environment.

Should be placed in server folder
```
DB_HOST=database
DB_NAME=snaily-cad
DB_USER=root
DB_PASSWORD=YOUR_DB_PW_HERE
JWT_SECRET=YOUR_JWT_SECRET_HERE
PROFILE=production
```

`docker-compose --env-file ./server/.env up`
`docker-compose down --rmi=local`

### CODE REVIEW

**Review by Dev-CasperTheGhost — APPROVED** [review]
Works like charm :tada:!

**Comment by bound2** [comment]
> 
> 
> Works like charm 🎉!

Thanks. Make sure to update Docker usage documentation as it is not able to start otherwise.

**Comment by Dev-CasperTheGhost** [comment]
> Make sure to update Docker usage documentation as it is not able to start otherwise.

Will do that now!

**Comment by Dev-CasperTheGhost** [comment]
Updated 😄

**Pull request merged**
